apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    certificate-authority-data: 
    server: https://127.0.0.1:55548
contexts:
- name: jenkins-context
  context:
    cluster: local
    user: jenkins
    namespace: disease-detector
current-context: jenkins-context
users:
- name: jenkins
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjJ5d3BBQ0dxcHh1bEczLS1GeUx6WkFVS3M3S3F6UnhlNE96NWZzQnpfUG8ifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzY1MzU2NjM5LCJpYXQiOjE3NjUzNTMwMzksImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiMjk1NDg4MDUtYmZkOS00ZmVjLWE4ZjItOGY5MThjNmZiNmFkIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkaXNlYXNlLWRldGVjdG9yIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImplbmtpbnMtc2VydmljZS1hY2NvdW50IiwidWlkIjoiOWM5YzJmM2UtZTM3My00NmMxLWEyNWMtZmYxMjYyYWMxNDIzIn19LCJuYmYiOjE3NjUzNTMwMzksInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkaXNlYXNlLWRldGVjdG9yOmplbmtpbnMtc2VydmljZS1hY2NvdW50In0.ayXA34xDmSWMEu3aQxMK-aUy5MAHEb9LOGYgRYMtVJm9vGT9wnaL7AxMV1scEar9QS3KUMIa6Z-YUs8uZHwhJsjV-10M8GvDTxbdGb_Q_0JV5XwseOcxgNQSXVcTzC1UPTQ2hvrFN76D4EVZg_d-Rfl8xb5tuHDyk0pAJP5o6YpICx_A7tjTMXsG9tqoh1LJegLCH5mKSck-NMTKRNHyQkkp7QVI-HrmmtmReExbIqDxUBBvinzIyklvj0Ry8cHD_IByeEi_-AJoGHEPhEvIWYbaEYOEKuNxOowZlOfNySS4VgMtkNPv1fXPnG3J79xy_eU71s2cWAjmDNQaIBbYkA
