apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: https://127.0.0.1:60552
    insecure-skip-tls-verify: true
contexts:
- name: jenkins-context
  context:
    cluster: local
    user: jenkins-sa
    namespace: disease-detector
current-context: jenkins-context
users:
- name: jenkins-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Il8xQ3ZnUGZQbFBuSDBEODE2dHd6MGxqMmcwM1JWVFM1Q0dUM3JzVHEwQWMifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzY1MzcyNTI5LCJpYXQiOjE3NjUzNjg5MjksImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiZjA0YTMzNjYtZDhhMS00NWYwLWI0MDAtMWRjMzEzMDVkZDZlIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkaXNlYXNlLWRldGVjdG9yIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImplbmtpbnMtc2VydmljZS1hY2NvdW50IiwidWlkIjoiZGVlMjhmZTktZGYxZC00NzVjLTllMTctMjExYTRjNmY2ODRhIn19LCJuYmYiOjE3NjUzNjg5MjksInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkaXNlYXNlLWRldGVjdG9yOmplbmtpbnMtc2VydmljZS1hY2NvdW50In0.HtWA33d8GAFOnDhDCbUOLEbPjU8YrjkxbqbeBXHP-UFSr_-3E6o_plYU8CuW3Jh785ybkDJ2lqCeeZsodcpfRT2ZTPZPpR9zoLd0Uw1EYN-kempum4PDD91Wp5ZmQNymrbJfNtaNG0R7BAu2vaUleAVIOqiQgE7Wza5pKPRkM9xSW03-9mTNdwVWrW_ljiwIyUJDi207jeUHHZ_1t2eCUrDHNNGmDcOCi20lzDFeYNXbmntvYTa0F-Dz3AOfLdFMKZdr580iYAjlX5-s4mvzIAhcVKM-BNMvpCsgWDgXCVxOho-d0SOn4MW39YTwqH-wW2b1hsetVHvwif7-fYSFNQ
