apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: https://127.0.0.1:60767
    insecure-skip-tls-verify: true
contexts:
- name: jenkins-context
  context:
    cluster: local
    user: jenkins-sa
    namespace: disease-detector
current-context: jenkins-context
users:
- name: jenkins-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ilg3ZWp2VmtmZmlVTW84bVh2bHp1TDZYOTQxODFlUzEyNVhTMGNzUTI1Z0UifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzY1NDc2ODQ0LCJpYXQiOjE3NjU0NzMyNDQsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiMzYwMmJhNjItOWNiNC00NDUzLWFhNTItMWFhMmE2NDBlOTcyIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkaXNlYXNlLWRldGVjdG9yIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImplbmtpbnMtc2VydmljZS1hY2NvdW50IiwidWlkIjoiODQ2NGUwODYtOGFkZC00ZGY1LWI1ZWQtMzg5MGE1NjhmMjdmIn19LCJuYmYiOjE3NjU0NzMyNDQsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkaXNlYXNlLWRldGVjdG9yOmplbmtpbnMtc2VydmljZS1hY2NvdW50In0.GjuNg-r3lhD0rL4ii0dj3qtur0empDZWaLLyS350LQPUA3vBZIrG5mAx2j5T4wy6T0EnbD-r8j0RPLnXASCAU9fkNGPPzpU7ThI2ZgZDGUdXHEvh-qeSnh1NQHsSb7QL53gGSGZnw9DDMfU47gLjABzgAseqIJchnWhuPoZJDd2vuLxrOPYcK6guGhmg5u1Y9uA6WMiN851EI3XcAvFn8JkRtcsI6BsEXn-jGYfZwcR6LbALJVY-44Y1FLwNMdpP4d6zRLcvx_FgWtA6cL8oj9blkKSinFKwadaAdLmy7IwrwASDI-KUj8F-pXGp_HL8W27Lm6zQ8E2HNse9cF7fmQ
