#apiVersion: v1
#kind: Config
#clusters:
#•⁠  ⁠name: local
#  cluster:
#    server: https://127.0.0.1:55607
#    insecure-skip-tls-verify: true
#contexts:
#•⁠  ⁠name: jenkins-context
#  context:
#    cluster: local
#    user: jenkins-sa
#    namespace: disease-detector
#current-context: jenkins-context
#users:
#•⁠  ⁠name: jenkins-sa
#  user:
#    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkdldGlWdXpySUp3cWxpRWJISV9EMjF3bFFBZy1Cd2hQRlF5YWM5MVEwTTgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzY1NTUyNzYyLCJpYXQiOjE3NjU0NjYzNjIsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiN2UxOGIwOWItZDQ0NS00Yjk0LWI0Y2UtZjQ1M2VkN2EwNWJkIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkaXNlYXNlLWRldGVjdG9yIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImplbmtpbnMtc2VydmljZS1hY2NvdW50IiwidWlkIjoiNmVkMTRiNmUtZTNjMy00YjY1LTljZGQtMDRlOGI4ZDdmYzI4In19LCJuYmYiOjE3NjU0NjYzNjIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkaXNlYXNlLWRldGVjdG9yOmplbmtpbnMtc2VydmljZS1hY2NvdW50In0.u-ov3_8sRqLBT1oeIfTjc45jDyjl7CNO0AAQ0DRabW6HV7S4_vRhgYkjl-OZfGEcQU_jb6i-EjD5OA8l7Hh3rGuTuuoIOxk3L6SIaH4CT0Cz3L3uGaJEZgZTSoEntgqJRqSNFKuu-e2rUHlYn1fL3SUDFdG2dTbk2zk2DUKLlKHJpcOkmc1m7ZE-nuFL37UMGHcu4hZ0gbpfvGUQRCEEZaxA_IRMMO4j8BTHy2ZXvWREwAvUHpY0QixfKT86vKrGzGFXwGm3s8VpA6avK_wa7E6QM6KNrWKGHDVq01pouroheMO-J9nIu8GBx4jf7wG3w5JewT9pFoafcbG6TPPiPw


apiVersion: v1
kind: Config
clusters:
  - name: local
    cluster:
      server: https://127.0.0.1:55607     # <-- put your api-server URL here
      insecure-skip-tls-verify: true

contexts:
  - name: jenkins-context
    context:
      cluster: local
      user: jenkins-sa
      namespace: disease-detector

current-context: jenkins-context

users:
  - name: jenkins-sa
    user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkdldGlWdXpySUp3cWxpRWJISV9EMjF3bFFBZy1Cd2hQRlF5YWM5MVEwTTgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzY1NTUyNzYyLCJpYXQiOjE3NjU0NjYzNjIsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiN2UxOGIwOWItZDQ0NS00Yjk0LWI0Y2UtZjQ1M2VkN2EwNWJkIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkaXNlYXNlLWRldGVjdG9yIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImplbmtpbnMtc2VydmljZS1hY2NvdW50IiwidWlkIjoiNmVkMTRiNmUtZTNjMy00YjY1LTljZGQtMDRlOGI4ZDdmYzI4In19LCJuYmYiOjE3NjU0NjYzNjIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkaXNlYXNlLWRldGVjdG9yOmplbmtpbnMtc2VydmljZS1hY2NvdW50In0.u-ov3_8sRqLBT1oeIfTjc45jDyjl7CNO0AAQ0DRabW6HV7S4_vRhgYkjl-OZfGEcQU_jb6i-EjD5OA8l7Hh3rGuTuuoIOxk3L6SIaH4CT0Cz3L3uGaJEZgZTSoEntgqJRqSNFKuu-e2rUHlYn1fL3SUDFdG2dTbk2zk2DUKLlKHJpcOkmc1m7ZE-nuFL37UMGHcu4hZ0gbpfvGUQRCEEZaxA_IRMMO4j8BTHy2ZXvWREwAvUHpY0QixfKT86vKrGzGFXwGm3s8VpA6avK_wa7E6QM6KNrWKGHDVq01pouroheMO-J9nIu8GBx4jf7wG3w5JewT9pFoafcbG6TPPiPw
