apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: https://127.0.0.1:60552
    insecure-skip-tls-verify: true
contexts:
- name: jenkins-context
  context:
    cluster: local
    user: jenkins-sa
    namespace: disease-detector
current-context: jenkins-context
users:
- name: jenkins-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Il8xQ3ZnUGZQbFBuSDBEODE2dHd6MGxqMmcwM1JWVFM1Q0dUM3JzVHEwQWMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkaXNlYXNlLWRldGVjdG9yIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImplbmtpbnMtc2VydmljZS1hY2NvdW50LXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImplbmtpbnMtc2VydmljZS1hY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZGVlMjhmZTktZGYxZC00NzVjLTllMTctMjExYTRjNmY2ODRhIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRpc2Vhc2UtZGV0ZWN0b3I6amVua2lucy1zZXJ2aWNlLWFjY291bnQifQ.LylzSbQhS-xxrphgiHo1dv-cSZfk8M7dc-p8lgtd8AO8gHzMaxRNs3E0bWyzBhF_phWZoHKEJLNq_cgrmRWQtTMGebOJzGEg1U75OAFrx5zeAIzYqr-hoKLquOlxmsAyFybDRdBD7LTfiSV6Hn0dQnmOg2GOHVueGHDCuuwZrultEWCCXcPwLxZPjcYZGaXAjVg03ifaJ-u9xpDB1B7EgXOObxyukoA61X7LNeEu4HnnCc1I0FjVXYgSqlzQZP5ngxuwUgWYbcMyuDRUQuFR0AA-TKYfuhoIWizkTUBY8a5wwEUb82oB77duXxTBnwiO2alhV-LcbhCVX6e1H2XkHw
