apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://127.0.0.1:49381
    insecure-skip-tls-verify: true
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    namespace: disease-detector
    user: jenkins-service-account
  name: jenkins-context
current-context: jenkins-context
users:
- name: jenkins-service-account
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImxRd2w2MTc0T2RrZjlCSmJZYUZoZmJOdWJuUGVrd2prb1F6eTN2bDlqX0UifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzk3MDIxMDM1LCJpYXQiOjE3NjU0ODUwMzUsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiNDY5YWJkMzMtZDVjNC00NTkyLWE3YmEtMjViZWY3ODAxYzMxIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkaXNlYXNlLWRldGVjdG9yIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImplbmtpbnMtc2VydmljZS1hY2NvdW50IiwidWlkIjoiZDUxYjIwMzMtNTllZS00NTAxLTk4OTEtYmJmOGVlNmE1MGJkIn19LCJuYmYiOjE3NjU0ODUwMzUsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkaXNlYXNlLWRldGVjdG9yOmplbmtpbnMtc2VydmljZS1hY2NvdW50In0.X24pgCefa2NThA804vydasY_QTqQcbeBKbyz14WEnrANsH2m9IG2rXv1mYs7k6PJzz7_LlJt8z3CEuLMBlSMHyFLSOUILtT0IdkzrqHHr7biRYV0IV7uuxZP5QesuCSvyAC9aIyIskS-lhgGanDWfKjB3zrbbcNqDJ9b6hXJM55SQyxhX6noSHdVODnVSOZTXIZHTGgm09voGBB4WhUPLBNBYpslwAW0qPIhmpAK4MzxkEj1AU2pjYo_Au4ts4EGMkj4crZlAzqWJgwLqjrNVAS2aqzM3TRGcBSJJPLSgL2rV-lFq16Wf_uc32lp-6T5Hgx27qrZsL0_GF4lTQPQeA
