apiVersion: v1
kind: Config
clusters:
- name: minikube
  cluster:
    server: https://127.0.0.1:57983
    insecure-skip-tls-verify: true
contexts:
- name: jenkins-context
  context:
    cluster: minikube
    user: jenkins-sa
    namespace: disease-detector
current-context: jenkins-context
users:
- name: jenkins-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ilg3ZWp2VmtmZmlVTW84bVh2bHp1TDZYOTQxODFlUzEyNVhTMGNzUTI1Z0UifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzY1NDc0MzU4LCJpYXQiOjE3NjU0NzA3NTgsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiZWYzZGI5NTktNGQzMi00OTA1LTg5OTgtODEwNzRiYTQ4YWJlIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkaXNlYXNlLWRldGVjdG9yIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImplbmtpbnMtc2VydmljZS1hY2NvdW50IiwidWlkIjoiODQ2NGUwODYtOGFkZC00ZGY1LWI1ZWQtMzg5MGE1NjhmMjdmIn19LCJuYmYiOjE3NjU0NzA3NTgsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkaXNlYXNlLWRldGVjdG9yOmplbmtpbnMtc2VydmljZS1hY2NvdW50In0.Hpny5iNZE4gYNqDwY1kBC7oUpuZPfSOOE6JbBIxn3lAKEz3moqIWo-vDbaL7GkbTZ2zV3BfnhneIo9xqKionnJmDW46YqbQm8VmS6oB-lP-y4Dq2KggykiFT9BQKY64D9JfcBTBRn6GS9rIhonp9deUvo52rTlU8Z9Gvy0be98mRkE2t4pTlhhCsTE5TSsys5oBXRoPd_1y4dU4uSs4WwyW3nziU-AlfyVsOqWr-xo-dD9ii0MdrSCDzo7P3G0xrLpJLmOSaexNc5GLXV7AkBifd-qcMgvDmNbl5HwJ6U2mocX-sDBSEVJ17XQtInjdwaHI8uBmgelD9CjjJKw0nsQ
